name: build-ios

on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: install packages
      run: brew install dpkg
    - name: make test
      run: make
