name: build-ios

on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: install packages
      run: brew install dpkg create-dmg ldid
    - name: make test
      run: make
    - name: upload artifact 
      uses: actions/upload-artifact@v4.0.0
      with:
       name: AnimeNow
       path: |
        App/*ipa
        App/*dmg
     
      
      
